name: share_image_whatsapp
description: A Flutter plugin to share content from your Flutter app to the WhatsApp share dialog.
version: 1.0.2
homepage: https://github.com/GianSandoval5/share_image_whatsapp

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  cross_file: ^0.3.4+2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  mime: ^2.0.0
  path_provider: ^2.1.5
  plugin_platform_interface: ^2.1.8
  url_launcher: ^6.3.1
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: share.imagewhatsapp.gs
        pluginClass: ShareWhatsappPlugin
      ios:
        pluginClass: ShareWhatsappPlugin
      linux:
        dartPluginClass: ShareWhatsappUrl
      macos:
        dartPluginClass: ShareWhatsappUrl
      windows:
        dartPluginClass: ShareWhatsappUrl
      web:
        pluginClass: ShareWhatsappWeb
        fileName: share_whatsapp_web.dart
